version: '3'

services:
    api:
        image: php:5.6
        depends_on:
            - mysql
        ports:
            - 80:80
        volumes:
            - ./app:/app
        working_dir: /app

    mysql:
        image: mysql:5
        env_file: .env-mysql
        volumes:
            - /tmp/mysql:/var/lib/mysql