version: '2'

services:

  app:
    build:
      context: ../
      dockerfile: docker/app-php/Dockerfile
    working_dir: /var/www
    volumes:
      - ../src:/var/www
    env_file: app-php/.env

  web:
    build: web
    working_dir: /var/www
    ports:
      - 8080:80

  database:
    build: database-mysql
    volumes:
      - dbdata:/var/lib/mysql
    env_file: database-mysql/.env
    ports:
      - "33061:3306"

volumes:
  dbdata:
