version: '2'

services:

  app:
    build:
      context: ../
      dockerfile: docker/app-php/Dockerfile
    working_dir: /var/www
    volumes:
      - ../src:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: database

  web:
    build: web
    working_dir: /var/www
    ports:
      - 8080:80

  database:
    build: database-mysql
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33061:3306"

volumes:
  dbdata:
